using AdDeliverableManager.Models;
using AdDeliverableManager.Security;
using AdDeliverableManager.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;

namespace AdDeliverableManager.Controllers;

[ApiController][Route("internal/changes")][Authorize]
public sealed class ChangesController : ControllerBase
{
    private readonly DatabaseService _database;private readonly DeliverableRepository _deliverables;private readonly PermissionService _permissions;
    public ChangesController(DatabaseService database,DeliverableRepository deliverables,PermissionService permissions){_database=database;_deliverables=deliverables;_permissions=permissions;}
    [HttpGet]public async Task<IActionResult> Get([FromQuery]string? status,CancellationToken ct){var allowed=await _permissions.GetAllowedDeliverableIdsAsync(User.GetUserId(),PermissionCatalog.ChangeView,ct);if(allowed is not null&&allowed.Count==0)return Ok(new{items=Array.Empty<object>()});await using var connection=await _database.OpenConnectionAsync(ct);await using var command=connection.CreateCommand();var scopeSql="";if(allowed is not null){var names=new List<string>();for(var i=0;i<allowed.Count;i++){var name="$scopeId"+i;names.Add(name);command.Parameters.AddWithValue(name,allowed[i]);}scopeSql=$" AND c.DeliverableId IN ({string.Join(',',names)})";}command.CommandText=$"SELECT c.Id,c.ChangeCode,d.DeliverableCode,d.UnifiedName,c.ChangeType,c.ChangeReason,c.ChangeContent,c.ImpactScope,c.RelatedIssueCode,c.Applicant,c.ResponsiblePerson,c.ChangeStatus,c.Reviewer,c.ReviewOpinion,c.PlannedCompletionDate,c.ActualCompletionDate,c.CreatedAt,c.UpdatedAt,c.FromVersionId,c.ToVersionId FROM ChangeRecords c JOIN Deliverables d ON d.Id=c.DeliverableId WHERE ($status IS NULL OR $status='' OR c.ChangeStatus=$status){scopeSql} ORDER BY c.UpdatedAt DESC";command.Parameters.AddValue("$status",status);var items=new List<object>();await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))items.Add(new{id=reader.GetInt32(0),code=reader.GetString(1),deliverableCode=reader.GetString(2),deliverableName=reader.GetString(3),changeType=reader.GetString(4),reason=reader.GetString(5),content=reader.GetString(6),impactScope=reader.GetNullableString(7),relatedIssueCode=reader.GetNullableString(8),applicant=reader.GetString(9),responsiblePerson=reader.GetString(10),status=reader.GetString(11),reviewer=reader.GetNullableString(12),reviewOpinion=reader.GetNullableString(13),plannedCompletionDate=reader.GetNullableString(14),actualCompletionDate=reader.GetNullableString(15),createdAt=reader.GetString(16),updatedAt=reader.GetString(17),fromVersionId=reader.IsDBNull(18)?(int?)null:reader.GetInt32(18),toVersionId=reader.IsDBNull(19)?(int?)null:reader.GetInt32(19)});return Ok(new{items});}
    [HttpPost]public async Task<IActionResult> Create([FromBody]ChangeCreateRequest request,CancellationToken ct){request.Applicant=User.GetDisplayName();if(request.DeliverableId<=0||string.IsNullOrWhiteSpace(request.ChangeReason)||string.IsNullOrWhiteSpace(request.ChangeContent)||string.IsNullOrWhiteSpace(request.ResponsiblePerson))return BadRequest(new{message="交付物、变更原因、变更内容和责任人不能为空。"});int fromVersionId;try{fromVersionId=await _deliverables.RequireCurrentReleasedBaselineAsync(request.DeliverableId,ct);}catch(KeyNotFoundException ex){return NotFound(new{message=ex.Message});}catch(InvalidOperationException ex){return Conflict(new{message=ex.Message});}await using var connection=await _database.OpenConnectionAsync(ct);using var transaction=connection.BeginTransaction();var now=DateTime.UtcNow.ToString("O");var changeCode=$"CHG-{DateTime.Now:yyyyMMddHHmmss}-{Random.Shared.Next(100,999)}";await using var command=connection.CreateCommand();command.Transaction=transaction;command.CommandText="INSERT INTO ChangeRecords(ChangeCode,DeliverableId,FromVersionId,ChangeType,ChangeReason,ChangeContent,ImpactScope,RelatedIssueCode,Applicant,ResponsiblePerson,ChangeStatus,PlannedCompletionDate,CreatedAt,UpdatedAt) VALUES($code,$deliverableId,$fromVersionId,$type,$reason,$content,$impact,$issue,$applicant,$owner,'PENDING_ASSESSMENT',$planned,$now,$now);SELECT last_insert_rowid();";command.Parameters.AddValue("$code",changeCode);command.Parameters.AddValue("$deliverableId",request.DeliverableId);command.Parameters.AddValue("$fromVersionId",fromVersionId);command.Parameters.AddValue("$type",request.ChangeType);command.Parameters.AddValue("$reason",request.ChangeReason.Trim());command.Parameters.AddValue("$content",request.ChangeContent.Trim());command.Parameters.AddValue("$impact",request.ImpactScope);command.Parameters.AddValue("$issue",request.RelatedIssueCode);command.Parameters.AddValue("$applicant",request.Applicant);command.Parameters.AddValue("$owner",request.ResponsiblePerson.Trim());command.Parameters.AddValue("$planned",request.PlannedCompletionDate);command.Parameters.AddValue("$now",now);var id=Convert.ToInt32(await command.ExecuteScalarAsync(ct));await InsertAuditAsync(connection,transaction,id,"CREATE",request.Applicant,$"发起变更 {changeCode}，锁定当前正式版本 #{fromVersionId}",now,ct);await transaction.CommitAsync(ct);return Ok(new{id,code=changeCode,fromVersionId,message="变更已发起并锁定当前正式版本。"});}
    [HttpPost("{id:int}/{action}")]public async Task<IActionResult> Action(int id,string action,[FromBody]ChangeActionRequest request,CancellationToken ct){var transitions=new Dictionary<string,(string Required,string Target)>(StringComparer.OrdinalIgnoreCase){{"approve",("PENDING_ASSESSMENT","APPROVED")},{"reject",("PENDING_ASSESSMENT","REJECTED")},{"start",("APPROVED","IMPLEMENTING")},{"verify",("IMPLEMENTING","PENDING_VERIFICATION")},{"close",("PENDING_VERIFICATION","CLOSED")}};if(!transitions.TryGetValue(action,out var transition))return BadRequest(new{message="不支持的变更操作。"});request.Operator=User.GetDisplayName();if((action.Equals("approve",StringComparison.OrdinalIgnoreCase)||action.Equals("reject",StringComparison.OrdinalIgnoreCase))&&string.IsNullOrWhiteSpace(request.Opinion))return BadRequest(new{message="批准或驳回时必须填写评审意见。"});await using var connection=await _database.OpenConnectionAsync(ct);using var transaction=connection.BeginTransaction();var now=DateTime.UtcNow.ToString("O");if(action.Equals("verify",StringComparison.OrdinalIgnoreCase)||action.Equals("close",StringComparison.OrdinalIgnoreCase)){await using var linkCheck=connection.CreateCommand();linkCheck.Transaction=transaction;linkCheck.CommandText="SELECT c.ChangeStatus,c.ToVersionId,v.InternalVersion,v.VersionStatus FROM ChangeRecords c LEFT JOIN DeliverableVersions v ON v.Id=c.ToVersionId WHERE c.Id=$id;";linkCheck.Parameters.AddValue("$id",id);await using var reader=await linkCheck.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))return NotFound(new{message="变更记录不存在。"});if(!string.Equals(reader.GetString(0),transition.Required,StringComparison.Ordinal))return Conflict(new{message="当前状态不允许执行该操作，请刷新后重试。"});if(reader.IsDBNull(1))return BadRequest(new{message="请先创建并关联变更后版本，再提交验证。"});if(action.Equals("close",StringComparison.OrdinalIgnoreCase)&&(reader.IsDBNull(3)||reader.GetString(3)!="RELEASED")){var version=reader.IsDBNull(2)?"变更版本":reader.GetString(2);return BadRequest(new{message=$"{version}尚未正式发布，不能关闭变更。"});}}
        await using var command=connection.CreateCommand();command.Transaction=transaction;command.CommandText="UPDATE ChangeRecords SET ChangeStatus=$target,Reviewer=CASE WHEN $target IN ('APPROVED','REJECTED') THEN $operator ELSE Reviewer END,ReviewOpinion=CASE WHEN $target IN ('APPROVED','REJECTED') THEN $opinion ELSE ReviewOpinion END,ToVersionId=COALESCE($toVersionId,ToVersionId),ActualCompletionDate=CASE WHEN $target='CLOSED' THEN $now ELSE ActualCompletionDate END,UpdatedAt=$now WHERE Id=$id AND ChangeStatus=$required";command.Parameters.AddValue("$target",transition.Target);command.Parameters.AddValue("$operator",request.Operator);command.Parameters.AddValue("$opinion",request.Opinion);command.Parameters.AddValue("$toVersionId",request.ToVersionId);command.Parameters.AddValue("$now",now);command.Parameters.AddValue("$id",id);command.Parameters.AddValue("$required",transition.Required);if(await command.ExecuteNonQueryAsync(ct)==0)return Conflict(new{message="当前状态不允许执行该操作，请刷新后重试。"});await InsertAuditAsync(connection,transaction,id,action.ToUpperInvariant(),request.Operator,$"变更状态：{transition.Required} → {transition.Target}",now,ct);await transaction.CommitAsync(ct);return Ok(new{status=transition.Target,message="变更状态已更新。"});}
    private static async Task InsertAuditAsync(Microsoft.Data.Sqlite.SqliteConnection c,Microsoft.Data.Sqlite.SqliteTransaction tx,int id,string action,string operatorName,string summary,string now,CancellationToken ct){await using var audit=c.CreateCommand();audit.Transaction=tx;audit.CommandText="INSERT INTO AuditLogs(EntityType,EntityId,ActionType,Operator,Summary,CreatedAt) VALUES('Change',$id,$action,$operator,$summary,$now)";audit.Parameters.AddValue("$id",id);audit.Parameters.AddValue("$action",action);audit.Parameters.AddValue("$operator",operatorName);audit.Parameters.AddValue("$summary",summary);audit.Parameters.AddValue("$now",now);await audit.ExecuteNonQueryAsync(ct);}
}
