using AdDeliverableManager.Models;
using AdDeliverableManager.Security;
using AdDeliverableManager.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AdDeliverableManager.Controllers;

[ApiController][Route("internal/change-workflow")][Authorize]
public sealed class ChangeWorkflowDataController : ControllerBase
{
    private readonly DatabaseService _database;private readonly DeliverableRepository _deliverables;private readonly PermissionService _permissions;
    public ChangeWorkflowDataController(DatabaseService database,DeliverableRepository deliverables,PermissionService permissions){_database=database;_deliverables=deliverables;_permissions=permissions;}
    [HttpGet]public async Task<IActionResult> List([FromQuery]string? status,CancellationToken ct){var allowed=await _permissions.GetAllowedDeliverableIdsAsync(User.GetUserId(),PermissionCatalog.ChangeView,ct);if(allowed.Count==0)return Ok(new{items=Array.Empty<object>()});await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();var names=new List<string>();for(var i=0;i<allowed.Count;i++){var name="$id"+i;names.Add(name);cmd.Parameters.AddWithValue(name,allowed[i]);}cmd.CommandText=$"SELECT c.Id,c.ChangeCode,d.Id,d.DeliverableCode,d.UnifiedName,t.TypeCode,c.ChangeType,c.ChangeReason,c.ChangeContent,c.ImpactScope,c.RelatedIssueCode,c.Applicant,c.ResponsiblePerson,c.ChangeStatus,c.Reviewer,c.ReviewOpinion,c.PlannedCompletionDate,c.ActualCompletionDate,c.CreatedAt,c.UpdatedAt,c.FromVersionId,fv.InternalVersion,c.ToVersionId,tv.InternalVersion,tv.VersionStatus FROM ChangeRecords c JOIN Deliverables d ON d.Id=c.DeliverableId JOIN DeliverableTypes t ON t.Id=d.DeliverableTypeId LEFT JOIN DeliverableVersions fv ON fv.Id=c.FromVersionId LEFT JOIN DeliverableVersions tv ON tv.Id=c.ToVersionId WHERE d.Id IN ({string.Join(',',names)}) AND ($status IS NULL OR $status='' OR c.ChangeStatus=$status) ORDER BY c.UpdatedAt DESC,c.Id DESC";cmd.Parameters.AddValue("$status",status);return Ok(new{items=await ReadItemsAsync(cmd,ct)});}
    [HttpGet("deliverable/{deliverableId:int}")]public async Task<IActionResult> Timeline(int deliverableId,CancellationToken ct){if(!await _permissions.HasPermissionAsync(User.GetUserId(),PermissionCatalog.ChangeView,deliverableId,ct))return Forbid();await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT c.Id,c.ChangeCode,d.Id,d.DeliverableCode,d.UnifiedName,t.TypeCode,c.ChangeType,c.ChangeReason,c.ChangeContent,c.ImpactScope,c.RelatedIssueCode,c.Applicant,c.ResponsiblePerson,c.ChangeStatus,c.Reviewer,c.ReviewOpinion,c.PlannedCompletionDate,c.ActualCompletionDate,c.CreatedAt,c.UpdatedAt,c.FromVersionId,fv.InternalVersion,c.ToVersionId,tv.InternalVersion,tv.VersionStatus FROM ChangeRecords c JOIN Deliverables d ON d.Id=c.DeliverableId JOIN DeliverableTypes t ON t.Id=d.DeliverableTypeId LEFT JOIN DeliverableVersions fv ON fv.Id=c.FromVersionId LEFT JOIN DeliverableVersions tv ON tv.Id=c.ToVersionId WHERE c.DeliverableId=$deliverableId ORDER BY c.UpdatedAt DESC,c.Id DESC";cmd.Parameters.AddWithValue("$deliverableId",deliverableId);var items=await ReadItemsAsync(cmd,ct);return Ok(new{deliverableId,total=items.Count,items});}
    [HttpPost]public async Task<IActionResult> Create([FromBody]ChangeCreateRequest request,CancellationToken ct){request.Applicant=User.GetDisplayName();if(request.DeliverableId<=0||string.IsNullOrWhiteSpace(request.ChangeReason)||string.IsNullOrWhiteSpace(request.ChangeContent)||string.IsNullOrWhiteSpace(request.ResponsiblePerson))return BadRequest(new{message="交付物、变更原因、变更内容和责任人不能为空。"});if(!await _permissions.HasPermissionAsync(User.GetUserId(),PermissionCatalog.ChangeCreate,request.DeliverableId,ct))return Forbid();int fromVersionId;try{fromVersionId=await _deliverables.RequireCurrentReleasedBaselineAsync(request.DeliverableId,ct);}catch(KeyNotFoundException ex){return NotFound(new{message=ex.Message});}catch(InvalidOperationException ex){return Conflict(new{message=ex.Message});}await using var c=await _database.OpenConnectionAsync(ct);using var tx=c.BeginTransaction();var now=DateTime.UtcNow.ToString("O");var changeCode=$"CHG-{DateTime.Now:yyyyMMddHHmmss}-{Random.Shared.Next(100,999)}";await using var insert=c.CreateCommand();insert.Transaction=tx;insert.CommandText="INSERT INTO ChangeRecords(ChangeCode,DeliverableId,FromVersionId,ChangeType,ChangeReason,ChangeContent,ImpactScope,RelatedIssueCode,Applicant,ResponsiblePerson,ChangeStatus,PlannedCompletionDate,CreatedAt,UpdatedAt) VALUES($code,$deliverableId,$fromVersionId,$type,$reason,$content,$impact,$issue,$applicant,$owner,'PENDING_ASSESSMENT',$planned,$now,$now);SELECT last_insert_rowid();";insert.Parameters.AddValue("$code",changeCode);insert.Parameters.AddValue("$deliverableId",request.DeliverableId);insert.Parameters.AddValue("$fromVersionId",fromVersionId);insert.Parameters.AddValue("$type",request.ChangeType);insert.Parameters.AddValue("$reason",request.ChangeReason.Trim());insert.Parameters.AddValue("$content",request.ChangeContent.Trim());insert.Parameters.AddValue("$impact",request.ImpactScope);insert.Parameters.AddValue("$issue",request.RelatedIssueCode);insert.Parameters.AddValue("$applicant",request.Applicant);insert.Parameters.AddValue("$owner",request.ResponsiblePerson.Trim());insert.Parameters.AddValue("$planned",request.PlannedCompletionDate);insert.Parameters.AddValue("$now",now);var id=Convert.ToInt32(await insert.ExecuteScalarAsync(ct));await using var audit=c.CreateCommand();audit.Transaction=tx;audit.CommandText="INSERT INTO AuditLogs(EntityType,EntityId,ActionType,Operator,Summary,CreatedAt) VALUES('Change',$id,'CREATE',$operator,$summary,$now)";audit.Parameters.AddValue("$id",id);audit.Parameters.AddValue("$operator",request.Applicant);audit.Parameters.AddValue("$summary",$"发起变更 {changeCode}，锁定当前正式版本 #{fromVersionId}");audit.Parameters.AddValue("$now",now);await audit.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return Ok(new{id,code=changeCode,fromVersionId,message="变更已发起并锁定当前正式版本。"});}
    private static async Task<List<object>> ReadItemsAsync(Microsoft.Data.Sqlite.SqliteCommand cmd,CancellationToken ct){var items=new List<object>();await using var reader=await cmd.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))items.Add(new{id=reader.GetInt32(0),code=reader.GetString(1),deliverableId=reader.GetInt32(2),deliverableCode=reader.GetString(3),deliverableName=reader.GetString(4),typeCode=reader.GetString(5),changeType=reader.GetString(6),reason=reader.GetString(7),content=reader.GetString(8),impactScope=reader.GetNullableString(9),relatedIssueCode=reader.GetNullableString(10),applicant=reader.GetString(11),responsiblePerson=reader.GetString(12),status=reader.GetString(13),reviewer=reader.GetNullableString(14),reviewOpinion=reader.GetNullableString(15),plannedCompletionDate=reader.GetNullableString(16),actualCompletionDate=reader.GetNullableString(17),createdAt=reader.GetString(18),updatedAt=reader.GetString(19),fromVersionId=reader.IsDBNull(20)?(int?)null:reader.GetInt32(20),fromVersion=reader.GetNullableString(21),toVersionId=reader.IsDBNull(22)?(int?)null:reader.GetInt32(22),toVersion=reader.GetNullableString(23),toVersionStatus=reader.GetNullableString(24)});return items;}
}
