using AdDeliverableManager.Security;

namespace AdDeliverableManager.Services;

public sealed class PermissionSchemaService
{
    private readonly DatabaseService _database;public PermissionSchemaService(DatabaseService database)=>_database=database;
    public async Task EnsureAsync(CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""
CREATE TABLE IF NOT EXISTS Roles(Id INTEGER PRIMARY KEY AUTOINCREMENT,Code TEXT NOT NULL UNIQUE COLLATE NOCASE,Name TEXT NOT NULL UNIQUE,Description TEXT,IsEnabled INTEGER NOT NULL DEFAULT 1,IsSystemRole INTEGER NOT NULL DEFAULT 0,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS Permissions(Id INTEGER PRIMARY KEY AUTOINCREMENT,Code TEXT NOT NULL UNIQUE,Name TEXT NOT NULL,Category TEXT NOT NULL,IsEnabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS RolePermissions(RoleId INTEGER NOT NULL,PermissionId INTEGER NOT NULL,PRIMARY KEY(RoleId,PermissionId),FOREIGN KEY(RoleId) REFERENCES Roles(Id) ON DELETE CASCADE,FOREIGN KEY(PermissionId) REFERENCES Permissions(Id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS UserRoles(UserId INTEGER NOT NULL,RoleId INTEGER NOT NULL,PRIMARY KEY(UserId,RoleId),FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE,FOREIGN KEY(RoleId) REFERENCES Roles(Id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS RoleWorkflowNodes(RoleId INTEGER NOT NULL,WorkflowNodeCode TEXT NOT NULL,PRIMARY KEY(RoleId,WorkflowNodeCode),FOREIGN KEY(RoleId) REFERENCES Roles(Id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS RoleDataScopes(Id INTEGER PRIMARY KEY AUTOINCREMENT,RoleId INTEGER NOT NULL,Dimension TEXT NOT NULL,ScopeType TEXT NOT NULL DEFAULT 'ALL',ScopeValue TEXT NOT NULL DEFAULT '',FOREIGN KEY(RoleId) REFERENCES Roles(Id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS IX_UserRoles_User ON UserRoles(UserId);CREATE INDEX IF NOT EXISTS IX_UserRoles_Role ON UserRoles(RoleId);CREATE INDEX IF NOT EXISTS IX_RolePermissions_Role ON RolePermissions(RoleId);CREATE INDEX IF NOT EXISTS IX_RoleWorkflowNodes_Role ON RoleWorkflowNodes(RoleId);CREATE INDEX IF NOT EXISTS IX_RoleDataScopes_RoleDimension ON RoleDataScopes(RoleId,Dimension);
""";await cmd.ExecuteNonQueryAsync(ct);await EnsureSystemAdminRoleAsync(ct);await SeedPermissionsAsync(ct);await SeedSystemAdminPolicyIfEmptyAsync(ct);await EnsureSystemAdminDataScopeAsync(ct);}
    private async Task EnsureSystemAdminRoleAsync(CancellationToken ct){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="INSERT OR IGNORE INTO Roles(Code,Name,Description,IsEnabled,IsSystemRole,CreatedBy,CreatedAt,UpdatedAt,Revision) VALUES('SYSTEM_ADMIN','系统管理员','系统初始管理员角色，可按需调整。',1,1,'SYSTEM',datetime('now'),datetime('now'),1)";await cmd.ExecuteNonQueryAsync(ct);}
    private async Task SeedPermissionsAsync(CancellationToken ct){await using var c=await _database.OpenConnectionAsync(ct);foreach(var p in PermissionCatalog.All){await using var cmd=c.CreateCommand();cmd.CommandText="INSERT OR IGNORE INTO Permissions(Code,Name,Category,IsEnabled) VALUES($code,$name,$category,1)";cmd.Parameters.AddWithValue("$code",p.Code);cmd.Parameters.AddWithValue("$name",p.Name);cmd.Parameters.AddWithValue("$category",p.Category);await cmd.ExecuteNonQueryAsync(ct);}}
    private async Task SeedSystemAdminPolicyIfEmptyAsync(CancellationToken ct){await using var c=await _database.OpenConnectionAsync(ct);await using var check=c.CreateCommand();check.CommandText="SELECT Id,(SELECT COUNT(*) FROM RolePermissions WHERE RoleId=Roles.Id) FROM Roles WHERE Code='SYSTEM_ADMIN'";await using var r=await check.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return;var roleId=r.GetInt32(0);var count=r.GetInt32(1);await r.DisposeAsync();if(count>0)return;foreach(var p in PermissionCatalog.All){await using var cmd=c.CreateCommand();cmd.CommandText="INSERT OR IGNORE INTO RolePermissions(RoleId,PermissionId) SELECT $role,Id FROM Permissions WHERE Code=$code";cmd.Parameters.AddWithValue("$role",roleId);cmd.Parameters.AddWithValue("$code",p.Code);await cmd.ExecuteNonQueryAsync(ct);}foreach(var n in PermissionCatalog.WorkflowNodes){await using var cmd=c.CreateCommand();cmd.CommandText="INSERT OR IGNORE INTO RoleWorkflowNodes(RoleId,WorkflowNodeCode) VALUES($role,$node)";cmd.Parameters.AddWithValue("$role",roleId);cmd.Parameters.AddWithValue("$node",n.Code);await cmd.ExecuteNonQueryAsync(ct);}}
    private async Task EnsureSystemAdminDataScopeAsync(CancellationToken ct){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO RoleDataScopes(RoleId,Dimension,ScopeType,ScopeValue) SELECT r.Id,'GLOBAL','ALL','' FROM Roles r WHERE r.Code='SYSTEM_ADMIN' AND NOT EXISTS(SELECT 1 FROM RoleDataScopes s WHERE s.RoleId=r.Id)";await cmd.ExecuteNonQueryAsync(ct);}
}
