using AdDeliverableManager.Models;
using Microsoft.Data.Sqlite;
namespace AdDeliverableManager.Services;
public sealed class PermissionService
{
    private readonly DatabaseService _database;public PermissionService(DatabaseService database)=>_database=database;
    public async Task<int?> ResolveDeliverableIdAsync(int id,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id FROM Deliverables WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);var value=await cmd.ExecuteScalarAsync(ct);return value is null?null:Convert.ToInt32(value);}
    public async Task<int?> ResolveDeliverableIdByVersionAsync(int versionId,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT DeliverableId FROM DeliverableVersions WHERE Id=$id";cmd.Parameters.AddWithValue("$id",versionId);var value=await cmd.ExecuteScalarAsync(ct);return value is null?null:Convert.ToInt32(value);}
    public async Task<int?> ResolveDeliverableIdByChangeAsync(int changeId,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT DeliverableId FROM ChangeRecords WHERE Id=$id";cmd.Parameters.AddWithValue("$id",changeId);var value=await cmd.ExecuteScalarAsync(ct);return value is null?null:Convert.ToInt32(value);}
    public async Task<IReadOnlyList<string>> GetEffectivePermissionsAsync(int userId,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT DISTINCT p.Code FROM UserRoles ur JOIN Roles r ON r.Id=ur.RoleId JOIN RolePermissions rp ON rp.RoleId=r.Id JOIN Permissions p ON p.Id=rp.PermissionId WHERE ur.UserId=$id AND r.IsEnabled=1 AND p.IsEnabled=1 ORDER BY p.Code";cmd.Parameters.AddWithValue("$id",userId);var list=new List<string>();await using var reader=await cmd.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))list.Add(reader.GetString(0));return list;}
    public async Task<IReadOnlyList<string>> GetEffectiveRoleNamesAsync(int userId,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT r.Name FROM UserRoles ur JOIN Roles r ON r.Id=ur.RoleId WHERE ur.UserId=$id AND r.IsEnabled=1 ORDER BY r.IsSystemRole DESC,r.Name";cmd.Parameters.AddWithValue("$id",userId);var list=new List<string>();await using var reader=await cmd.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))list.Add(reader.GetString(0));return list;}
    public async Task<bool> HasPermissionAsync(int userId,string permissionCode,int? deliverableId=null,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);var roles=await GetRoleIdsAsync(c,userId,ct);foreach(var roleId in roles){if(!await RoleHasPermissionAsync(c,roleId,permissionCode,ct))continue;if(!deliverableId.HasValue||await MatchesDataScopeAsync(c,roleId,deliverableId.Value,ct))return true;}return false;}
    public async Task<bool> HasCreateScopeAsync(int userId,string permissionCode,int departmentId,int projectId,int typeId,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);var roles=await GetRoleIdsAsync(c,userId,ct);foreach(var roleId in roles){if(!await RoleHasPermissionAsync(c,roleId,permissionCode,ct))continue;if(await MatchesDataScopeAsync(c,roleId,departmentId,projectId,typeId,ct))return true;}return false;}
    public async Task<IReadOnlyList<int>> GetAllowedDeliverableIdsAsync(int userId,string permissionCode,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);var roles=await GetRoleIdsAsync(c,userId,ct);if(roles.Count==0)return [];var permittedRoles=new List<int>();foreach(var roleId in roles)if(await RoleHasPermissionAsync(c,roleId,permissionCode,ct))permittedRoles.Add(roleId);if(permittedRoles.Count==0)return [];var rows=new List<(int Id,int DepartmentId,int ProjectId,int TypeId)>();await using(var cmd=c.CreateCommand()){cmd.CommandText="SELECT Id,DepartmentId,ProjectId,DeliverableTypeId FROM Deliverables WHERE LifecycleStatus <> 'ARCHIVED'";await using var reader=await cmd.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))rows.Add((reader.GetInt32(0),reader.GetInt32(1),reader.GetInt32(2),reader.GetInt32(3)));}var ids=new List<int>();foreach(var row in rows){foreach(var roleId in permittedRoles){if(await MatchesDataScopeAsync(c,roleId,row.DepartmentId,row.ProjectId,row.TypeId,ct)){ids.Add(row.Id);break;}}}return ids;}
    public static string BuildDataScopePredicate(string deliverableAlias,string permissionCode)
    {
        var a=string.IsNullOrWhiteSpace(deliverableAlias)?"d":deliverableAlias;
        return $@"EXISTS (
            SELECT 1 FROM UserRoles ur JOIN Roles r ON r.Id=ur.RoleId AND r.IsEnabled=1
            JOIN RolePermissions rp ON rp.RoleId=r.Id
            JOIN Permissions p ON p.Id=rp.PermissionId AND p.IsEnabled=1 AND p.Code='{permissionCode.Replace("'","''")}'
            WHERE ur.UserId=$scopeUserId
              AND EXISTS (SELECT 1 FROM RoleDataScopes s0 WHERE s0.RoleId=r.Id)
              AND ((NOT EXISTS (SELECT 1 FROM RoleDataScopes s1 WHERE s1.RoleId=r.Id AND s1.Dimension='DEPARTMENT') OR EXISTS (SELECT 1 FROM RoleDataScopes s1 WHERE s1.RoleId=r.Id AND s1.Dimension='DEPARTMENT' AND (s1.ScopeType='ALL' OR (s1.ScopeType='INCLUDE' AND s1.ScopeValue=CAST({a}.DepartmentId AS TEXT)))))
                AND (NOT EXISTS (SELECT 1 FROM RoleDataScopes s2 WHERE s2.RoleId=r.Id AND s2.Dimension='PROJECT') OR EXISTS (SELECT 1 FROM RoleDataScopes s2 WHERE s2.RoleId=r.Id AND s2.Dimension='PROJECT' AND (s2.ScopeType='ALL' OR (s2.ScopeType='INCLUDE' AND s2.ScopeValue=CAST({a}.ProjectId AS TEXT)))))
                AND (NOT EXISTS (SELECT 1 FROM RoleDataScopes s3 WHERE s3.RoleId=r.Id AND s3.Dimension='TYPE') OR EXISTS (SELECT 1 FROM RoleDataScopes s3 WHERE s3.RoleId=r.Id AND s3.Dimension='TYPE' AND (s3.ScopeType='ALL' OR (s3.ScopeType='INCLUDE' AND s3.ScopeValue=CAST({a}.DeliverableTypeId AS TEXT)))))
              )
        )";
    }
    private static async Task<bool> RoleHasPermissionAsync(SqliteConnection c,int roleId,string permissionCode,CancellationToken ct){await using var cmd=c.CreateCommand();cmd.CommandText="SELECT COUNT(*) FROM RolePermissions rp JOIN Permissions p ON p.Id=rp.PermissionId WHERE rp.RoleId=$role AND p.Code=$code AND p.IsEnabled=1";cmd.Parameters.AddWithValue("$role",roleId);cmd.Parameters.AddWithValue("$code",permissionCode);return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct))>0;}
    private static async Task<List<int>> GetRoleIdsAsync(SqliteConnection c,int userId,CancellationToken ct){await using var cmd=c.CreateCommand();cmd.CommandText="SELECT r.Id FROM UserRoles ur JOIN Roles r ON r.Id=ur.RoleId WHERE ur.UserId=$id AND r.IsEnabled=1";cmd.Parameters.AddWithValue("$id",userId);var ids=new List<int>();await using var reader=await cmd.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))ids.Add(reader.GetInt32(0));return ids;}
    private static async Task<bool> MatchesDataScopeAsync(SqliteConnection c,int roleId,int deliverableId,CancellationToken ct){await using var cmd=c.CreateCommand();cmd.CommandText="SELECT DepartmentId,ProjectId,DeliverableTypeId FROM Deliverables WHERE Id=$id";cmd.Parameters.AddWithValue("$id",deliverableId);int departmentId,projectId,typeId;await using(var reader=await cmd.ExecuteReaderAsync(ct)){if(!await reader.ReadAsync(ct))return false;departmentId=reader.GetInt32(0);projectId=reader.GetInt32(1);typeId=reader.GetInt32(2);}return await MatchesDataScopeAsync(c,roleId,departmentId,projectId,typeId,ct);}
    private static async Task<bool> MatchesDataScopeAsync(SqliteConnection c,int roleId,int departmentId,int projectId,int typeId,CancellationToken ct){await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Dimension,ScopeType,ScopeValue FROM RoleDataScopes WHERE RoleId=$role";cmd.Parameters.AddWithValue("$role",roleId);var scopes=new List<(string Dimension,string ScopeType,string ScopeValue)>();await using(var reader=await cmd.ExecuteReaderAsync(ct)){while(await reader.ReadAsync(ct))scopes.Add((reader.GetString(0),reader.GetString(1),reader.GetString(2)));}if(scopes.Count==0)return false;var values=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{DataScopeCatalog.Department,departmentId.ToString()},{DataScopeCatalog.Project,projectId.ToString()},{DataScopeCatalog.Type,typeId.ToString()}};foreach(var group in scopes.GroupBy(x=>x.Dimension,StringComparer.OrdinalIgnoreCase)){if(group.Any(x=>x.ScopeType.Equals(DataScopeCatalog.All,StringComparison.OrdinalIgnoreCase)))continue;if(!values.TryGetValue(group.Key,out var value)||!group.Any(x=>x.ScopeType.Equals(DataScopeCatalog.Include,StringComparison.OrdinalIgnoreCase)&&x.ScopeValue.Equals(value,StringComparison.OrdinalIgnoreCase)))return false;}return true;}
}
