using AdDeliverableManager.Models;
using Microsoft.Data.Sqlite;

namespace AdDeliverableManager.Services;

public sealed class PermissionUserRepository
{
    private readonly DatabaseService _database;private readonly PasswordService _passwords;
    public PermissionUserRepository(DatabaseService database,PasswordService passwords){_database=database;_passwords=passwords;}
    public async Task<IReadOnlyList<object>> ListAsync(CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT u.Id,u.Username,u.DisplayName,u.IsEnabled,u.MustChangePassword,u.LastLoginAt,u.UpdatedAt,u.Revision,COALESCE(GROUP_CONCAT(r.Name,'、'),'未分配角色') FROM Users u LEFT JOIN UserRoles ur ON ur.UserId=u.Id LEFT JOIN Roles r ON r.Id=ur.RoleId GROUP BY u.Id,u.Username,u.DisplayName,u.IsEnabled,u.MustChangePassword,u.LastLoginAt,u.UpdatedAt,u.Revision ORDER BY u.Username";var rows=new List<object>();await using var rd=await cmd.ExecuteReaderAsync(ct);while(await rd.ReadAsync(ct))rows.Add(new{id=rd.GetInt32(0),username=rd.GetString(1),displayName=rd.GetString(2),isEnabled=rd.GetInt32(3)==1,mustChangePassword=rd.GetInt32(4)==1,lastLoginAt=rd.IsDBNull(5)?null:rd.GetString(5),updatedAt=rd.GetString(6),revision=rd.GetInt32(7),roles=rd.GetString(8)});return rows;}
    public async Task<int> CreateAsync(UserCreateV08Request req,string op,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(req.Username)||string.IsNullOrWhiteSpace(req.DisplayName)||req.RoleIds.Length==0)throw new ArgumentException("用户名、显示名称和至少一个角色不能为空。");if(string.IsNullOrWhiteSpace(req.Password))throw new ArgumentException("初始密码不能为空。");var username=req.Username.Trim();if(username.Length is <3 or >40||username.Any(c=>!(char.IsLetterOrDigit(c)||c is '.' or '_' or '-')))throw new ArgumentException("用户名需为3-40位字母、数字、点、下划线或短横线。");var(hash,salt)=_passwords.HashPassword(req.Password);await using var c=await _database.OpenConnectionAsync(ct);using var tx=c.BeginTransaction();await using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO Users(Username,DisplayName,PasswordHash,PasswordSalt,IsEnabled,MustChangePassword,CreatedBy,CreatedAt,UpdatedAt,Revision) VALUES($u,$d,$h,$s,1,$m,$by,$now,$now,1);SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$u",username);cmd.Parameters.AddWithValue("$d",req.DisplayName.Trim());cmd.Parameters.AddWithValue("$h",hash);cmd.Parameters.AddWithValue("$s",salt);cmd.Parameters.AddWithValue("$m",req.MustChangePassword?1:0);cmd.Parameters.AddWithValue("$by",op);cmd.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));int id;try{id=Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}catch(SqliteException ex)when(ex.SqliteErrorCode==19){throw new InvalidOperationException("用户名已经存在。");}foreach(var role in req.RoleIds.Distinct()){await using var r=c.CreateCommand();r.Transaction=tx;r.CommandText="INSERT INTO UserRoles(UserId,RoleId) SELECT $user,Id FROM Roles WHERE Id=$role AND IsEnabled=1";r.Parameters.AddWithValue("$user",id);r.Parameters.AddWithValue("$role",role);if(await r.ExecuteNonQueryAsync(ct)==0)throw new InvalidOperationException("所选角色不存在或已停用。");}await tx.CommitAsync(ct);return id;}
    public async Task<bool> UpdateAsync(int id,UserUpdateV08Request req,int currentUserId,string op,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(req.DisplayName)||req.RoleIds.Length==0)throw new ArgumentException("显示名称和至少一个角色不能为空。");if(id==currentUserId&&!req.IsEnabled)throw new InvalidOperationException("不能停用当前登录账号。");await using var c=await _database.OpenConnectionAsync(ct);using var tx=c.BeginTransaction();await using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="UPDATE Users SET DisplayName=$d,IsEnabled=$e,UpdatedAt=$now,Revision=Revision+1 WHERE Id=$id AND Revision=$rev";cmd.Parameters.AddWithValue("$d",req.DisplayName.Trim());cmd.Parameters.AddWithValue("$e",req.IsEnabled?1:0);cmd.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);cmd.Parameters.AddWithValue("$rev",req.Revision);if(await cmd.ExecuteNonQueryAsync(ct)==0)return false;await using var clear=c.CreateCommand();clear.Transaction=tx;clear.CommandText="DELETE FROM UserRoles WHERE UserId=$id";clear.Parameters.AddWithValue("$id",id);await clear.ExecuteNonQueryAsync(ct);foreach(var role in req.RoleIds.Distinct()){await using var r=c.CreateCommand();r.Transaction=tx;r.CommandText="INSERT INTO UserRoles(UserId,RoleId) SELECT $user,Id FROM Roles WHERE Id=$role AND IsEnabled=1";r.Parameters.AddWithValue("$user",id);r.Parameters.AddWithValue("$role",role);if(await r.ExecuteNonQueryAsync(ct)==0)throw new InvalidOperationException("所选角色不存在或已停用。");}await tx.CommitAsync(ct);return true;}
    public async Task<IReadOnlyList<int>> GetRoleIdsAsync(int userId,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT RoleId FROM UserRoles WHERE UserId=$id";cmd.Parameters.AddWithValue("$id",userId);var ids=new List<int>();await using var rd=await cmd.ExecuteReaderAsync(ct);while(await rd.ReadAsync(ct))ids.Add(rd.GetInt32(0));return ids;}
}
