using AdDeliverableManager.Models;
using AdDeliverableManager.Security;
using Microsoft.Data.Sqlite;

namespace AdDeliverableManager.Services;

public sealed class UserRepository
{
    private readonly DatabaseService _database;private readonly PasswordService _passwords;
    public UserRepository(DatabaseService database,PasswordService passwords){_database=database;_passwords=passwords;}
    public async Task<int> CountAsync(CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT COUNT(*) FROM Users";return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}
    public async Task<UserRecord?> FindByUsernameAsync(string username,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Username,DisplayName,PasswordHash,PasswordSalt,IsEnabled,MustChangePassword,LastLoginAt,Revision FROM Users WHERE Username=$username COLLATE NOCASE";cmd.Parameters.AddWithValue("$username",username.Trim());await using var r=await cmd.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?ReadUser(r):null;}
    public async Task<UserRecord?> FindByIdAsync(int id,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Username,DisplayName,PasswordHash,PasswordSalt,IsEnabled,MustChangePassword,LastLoginAt,Revision FROM Users WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);await using var r=await cmd.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?ReadUser(r):null;}
    public async Task<int> BootstrapAdminAsync(BootstrapAdminRequest request,CancellationToken ct=default)
    {if(await CountAsync(ct)>0)throw new InvalidOperationException("系统已经完成管理员初始化。");var username=NormalizeUsername(request.Username);if(string.IsNullOrWhiteSpace(request.DisplayName))throw new ArgumentException("显示名称不能为空。");var(hash,salt)=_passwords.HashPassword(request.Password);var now=DateTime.UtcNow.ToString("O");await using var c=await _database.OpenConnectionAsync(ct);using var tx=c.BeginTransaction();await using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO Users(Username,DisplayName,PasswordHash,PasswordSalt,IsEnabled,MustChangePassword,CreatedBy,CreatedAt,UpdatedAt,Revision) VALUES($u,$d,$h,$s,1,0,'SYSTEM_BOOTSTRAP',$now,$now,1);SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$u",username);cmd.Parameters.AddWithValue("$d",request.DisplayName.Trim());cmd.Parameters.AddWithValue("$h",hash);cmd.Parameters.AddWithValue("$s",salt);cmd.Parameters.AddWithValue("$now",now);int userId;try{userId=Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}catch(SqliteException ex)when(ex.SqliteErrorCode==19){throw new InvalidOperationException("用户名已经存在。");}await EnsureSystemAdminRoleAsync(c,tx,userId,ct);await tx.CommitAsync(ct);return userId;}
    public async Task ChangePasswordAsync(int userId,string currentPassword,string newPassword,CancellationToken ct=default){var user=await FindByIdAsync(userId,ct)??throw new KeyNotFoundException("用户不存在。");if(!_passwords.Verify(currentPassword,user.PasswordHash,user.PasswordSalt))throw new InvalidOperationException("当前密码不正确。");var(hash,salt)=_passwords.HashPassword(newPassword);await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE Users SET PasswordHash=$h,PasswordSalt=$s,MustChangePassword=0,UpdatedAt=$now,Revision=Revision+1 WHERE Id=$id";cmd.Parameters.AddWithValue("$h",hash);cmd.Parameters.AddWithValue("$s",salt);cmd.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",userId);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task MarkLoginAsync(int id,CancellationToken ct=default){await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE Users SET LastLoginAt=$now,UpdatedAt=$now WHERE Id=$id";cmd.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task ResetPasswordAsync(int id,UserResetPasswordRequest request,string operatorName,CancellationToken ct=default){var(hash,salt)=_passwords.HashPassword(request.NewPassword);await using var c=await _database.OpenConnectionAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE Users SET PasswordHash=$h,PasswordSalt=$s,MustChangePassword=$m,UpdatedAt=$now,Revision=Revision+1 WHERE Id=$id";cmd.Parameters.AddWithValue("$h",hash);cmd.Parameters.AddWithValue("$s",salt);cmd.Parameters.AddWithValue("$m",request.MustChangePassword?1:0);cmd.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);if(await cmd.ExecuteNonQueryAsync(ct)==0)throw new KeyNotFoundException("用户不存在。");}
    private static UserRecord ReadUser(SqliteDataReader r)=>new(r.GetInt32(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetInt32(5)==1,r.GetInt32(6)==1,r.IsDBNull(7)?null:r.GetString(7),r.GetInt32(8));
    private static string NormalizeUsername(string value){var x=value.Trim();if(x.Length is <3 or >40||x.Any(c=>!(char.IsLetterOrDigit(c)||c is '.' or '_' or '-')))throw new ArgumentException("用户名需为3-40位字母、数字、点、下划线或短横线。");return x;}
    private static async Task EnsureSystemAdminRoleAsync(SqliteConnection c,SqliteTransaction tx,int userId,CancellationToken ct){await using var role=c.CreateCommand();role.Transaction=tx;role.CommandText="SELECT Id FROM Roles WHERE Code=$code AND IsEnabled=1";role.Parameters.AddWithValue("$code",AppRoles.SystemAdminCode);var roleId=Convert.ToInt32(await role.ExecuteScalarAsync(ct)??0);if(roleId<=0)throw new InvalidOperationException("系统管理员角色未初始化。");await using var link=c.CreateCommand();link.Transaction=tx;link.CommandText="INSERT INTO UserRoles(UserId,RoleId) VALUES($user,$role)";link.Parameters.AddWithValue("$user",userId);link.Parameters.AddWithValue("$role",roleId);await link.ExecuteNonQueryAsync(ct);}
}
